### ISSUE TITLE
Star history not showing up properly in README

### ISSUE THREAD

**Issue by aacitelli** [aacitelli/typescript-serverless-monorepo-template#33]
### Bug description

Just showing as the embed code, not the actual embed.

**Comment by Ankit6989** [comment]
hey can you explain the issue a little and what changes you require specifically

**Comment by aacitelli** [comment]
> hey can you explain the issue a little and what changes you require specifically

Sure. The embed in the readme isn't working like I expected it to.

![image](https://user-images.githubusercontent.com/30580900/231939276-342f1a8f-436e-47d0-b1b6-61bb6bae78ce.png)

It's just the embed text rather than the actual embed.

**Comment by 1bhavyasingh1** [comment]
Hey @aacitelli  I would like to work on this
